server {
    listen 80;
    listen [::]:80;
    server_name orosaga.wanhuchangan.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/acme;
        default_type text/plain;
        try_files $uri =404;
    }

    error_page 503 /503.html;

    location / {
        return 503;
    }

    location = /503.html {
        root /var/www/orosaga-maintenance;
        internal;
    }
}
